In [1]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch

In [59]:
a = torch.ones((2,3),requires_grad = True)
print(a)
b = a + 5
print(b)
c = b ** 2
print(c)
out = c.mean()
print(out)
out.backward()
print(a.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)
tensor([[36., 36., 36.],
        [36., 36., 36.]], grad_fn=<PowBackward0>)
tensor(36., grad_fn=<MeanBackward0>)
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [51]:
a = torch.ones((3,3),requires_grad = True)
print(a)
b = a + 5
print(b)
c = b ** 2
print(c)
out = c.mean()
print(out)
out.backward()

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)
tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<PowBackward0>)
tensor(36., grad_fn=<MeanBackward0>)


In [52]:
print(a.grad)

tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [54]:
a = torch.ones((3,3),requires_grad = True)
print(a)
b = a + 5
print(b)
c = b ** 2
print(c)
out = c.sum()
print(out)
out.backward()
print(a.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)
tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<PowBackward0>)
tensor(324., grad_fn=<SumBackward0>)
tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])


In [46]:
a = torch.tensor([[2.,2.],[2.,2.]],requires_grad = True)
print(a)
b = a + 5
print(b)
c = b ** 2
print(c)
out = c.sum()
print(out)
out.backward()

tensor([[2., 2.],
        [2., 2.]], requires_grad=True)
tensor([[7., 7.],
        [7., 7.]], grad_fn=<AddBackward0>)
tensor([[49., 49.],
        [49., 49.]], grad_fn=<PowBackward0>)
tensor(196., grad_fn=<SumBackward0>)


In [47]:
print(a.grad)

tensor([[14., 14.],
        [14., 14.]])


In [38]:
a = torch.tensor([[3.,3.],[3.,3.]],requires_grad = True)
print(a)
b = a + 2
print(b)
c = b ** 2
print(c)
out = c.sum()
print(out)
out.backward()

tensor([[3., 3.],
        [3., 3.]], requires_grad=True)
tensor([[5., 5.],
        [5., 5.]], grad_fn=<AddBackward0>)
tensor([[25., 25.],
        [25., 25.]], grad_fn=<PowBackward0>)
tensor(100., grad_fn=<SumBackward0>)


In [39]:
print(a.grad)

tensor([[10., 10.],
        [10., 10.]])
