In [2]:
import numpy as np

Numpy는 "Numerical Python"의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공

- Numerical Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
- 넘파이의 기본 데이터 타입은 ndarray.ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

numpy 특징

- 강력한 N차원 배열 객체
- 정교한 브로드캐스팅 기능
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

복습시험출제

In [ ]:
!pip install numpy

In [450]:
import numpy as np
z = np.arange(10) # 복습시험출제
print(z,type(z))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [451]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [452]:
%time for _ in range(10): my_array2 = my_arr*2 # 복습시험출제

Wall time: 13 ms


In [453]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 609 ms


In [454]:
# 배열 연산
# np.random.randn 가우시안 표준 정규분표에서 난수 매트릭스 array 생성
# 가우시안 표준 정규분표(평균이 0, 표준편차가 1)
data = np.random.randn(2,3) # 표준 정규분포로 구성되는 2행 3열 매트릭스 복습시험출제
print(data, '\n')
print(data*10,'\n')
print(data*data,'\n')

[[ 2.34290579 -1.38508075 -0.12607945]
 [-1.06759006  0.18777285 -1.83891845]] 

[[ 23.42905788 -13.85080755  -1.26079449]
 [-10.67590064   1.87772855 -18.38918449]] 

[[5.48920753 1.9184487  0.01589603]
 [1.13974854 0.03525865 3.38162106]] 



In [455]:
print(data.shape) # 행렬의 크기 복습시험출제
print(data.dtype) # 데이터 타입 
print(data.ndim) # 차원

(2, 3)
float64
2


다차원 배열
<img src = 'numpy차원.jpg' STYLE = 'width:300px;'>

In [ ]:
data2 = [[1,2,3,4],[5,6,7,8]]
print(type(data2),'\n')
arr2 = np.array(data2)
print(arr2,type(arr2))

In [ ]:
print(arr2.ndim,'\n')
print(arr2.shape,'\n')

In [3]:
# 1차원 배열로 3개의 데이터
array1 = np.array([1,2,3])
print(array1,array1.shape,type(array1)) # (,열)이 아닌 (열,) 형태로 출력

[1 2 3] (3,) <class 'numpy.ndarray'>


In [4]:
# 2차원 배열로 2개의 row와 3개의 column으로 구성된 6개의 데이터 복습시험출제
array2 = np.array([[1,2,3],[4,5,6]])
print(array2,array2.ndim,array2.shape)

[[1 2 3]
 [4 5 6]] 2 (2, 3)


In [ ]:
# 1개의 row와 3개의 column으로 구성된 2차원 배열
array21 = np.array([[1,2,3]])
print(array21,array21.ndim,array21.shape)

In [ ]:
# 3차원 복습시험출제
array3 = np.array([[[1,2,3],[2,3,4]],
                   [[3,4,5],[4,5,6]],
                   [[5,6,7],[6,7,8]]])
print(array3,'\n\n',array3.shape,'\n',array3.ndim,'\n',type(array3))

In [ ]:
# 경고 메시지 제외 처리
import warnings
warnings.filterwarnings('ignore')

배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

복습시험출제

In [485]:
print(np.zeros(10),'\n')복습시험출제
print(np.zeros((3,6)),'\n')
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
print(np.ones((2,3,2),dtype = int)) # dtype 로 타입설정 가능(int,float등)

In [ ]:
ar1 = np.full((2,2),5)
print(ar1)

In [7]:
# 항등행렬, 단위행렬을 만듦
ar2 = np.eye(3)
print(ar2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# [과제] zeros_like, ones_like, full_like 함수 활용해서 하나씩 만들어보기
import numpy as np
arr1 = np.arange(9).reshape(3,3)
z = np.zeros_like(arr1)
o = np.ones_like(arr1)
f = np.full_like(arr1,5)
print(z,'\n')
print(o,'\n')
print(f,'\n')

[[0 0 0]
 [0 0 0]
 [0 0 0]] 

[[1 1 1]
 [1 1 1]
 [1 1 1]] 

[[5 5 5]
 [5 5 5]
 [5 5 5]] 



In [ ]:
# arrange 함수 : python의 range함수의 배열버전 복습시험출제
arr1 = np.arange(30)
arr1

In [ ]:
arr2 = arr1.reshape(3,10)
print(arr2,'\n')
arr3 = arr1.reshape(2,3,5)
print(arr3)

In [ ]:
# Q. array1을 생성하고 reshape 함수를 이용, (5,2) 배열을 생성하고 크기를 같이 출력하세요.
array1 = np.arange(10)
array2 = array1.reshape(5,2)
print(array2)

In [ ]:
# 0~29 일차원 배열을 생성한 후 다시 2,3차원 배열로 변환하여 출력하세요. 복습시험출제
arr1 = np.arange(30)
arr2 = arr1.reshape(3,10)
print(arr2,'\n')
arr3 = arr1.reshape(2,3,5)
print(arr3)

In [ ]:
# reshape(-1,-1) 이용, 차원 변경 복습시험출제
array1 = np.arange(30)
ar12 = array1.reshape(3,-1)
print(ar12,ar12.shape,'\n')
ar13 = array1.reshape(-1,2,5)
print(ar13,ar13.shape)

In [ ]:
# 2 -> 1, 3 차원으로 변환하여 출력
ar3 = ar12.reshape(3,2,5)
print(ar3,'\n')
ar1 = ar12.reshape(-1,)
print(ar1)

In [ ]:
# 3 -> 1,2차원으로 변환하여 출력
ar3

In [ ]:
ar1 = ar3.reshape(-1,)
ar2 = ar3.reshape(3,-1)
print(ar1,'\n',ar1.shape)
print(ar2,'\n',ar2.shape)

행렬의 종류  복습시험출제
- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을 때 항등행렬이 나오는 행렬

In [ ]:
# 정방행렬
ar1 = np.full((5,5),7)
print(ar1)

In [ ]:
# 항등행렬, 단위행렬
a = np.eye(5)
print(a)

In [ ]:
# 영행렬
a = np.zeros((5,5))
print(a)

In [ ]:
# 전치행렬 , 직교랭렬

ndarray 데이터 형태 지정 및 변경 복습시험출제
<img src = '데이터형태.jpg' STYLE = 'width:300px;'>

In [ ]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)
print(arr1,arr1.dtype,'\n')
print(arr2,arr2.dtype)

In [ ]:
# 타입 변경
arr = np.array([1,2,3,4,5])
print(arr,arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

In [ ]:
# empty 함수 : shape와 dtype을 입력받아 초기화되지 않은 배열을 만들어준다. cf. zeros 함수
# empty 함수를 실행할 때마다 값이 다른것을 확인할 수 있다. 이는 해당 메모리 영역에 어떤 데이터가 남아있었던지 상관없이
# 그대로 영역의 주소만 알려줄 뿐 초기화는 사용자에게 맡기기 때문임.

print(np.empty(shape=(10,),dtype = np.int8)) # 복습시험출제

In [11]:
# 문자열 타입으로 배열 만들기 복습시험출제
# arr = np.array([1,2,3,4],dtype = 'S')
arr = np.array([1,2,3,4],dtype = np.string_)
print(arr,arr.dtype)

[b'1' b'2' b'3' b'4'] |S1


In [ ]:
arr1 = arr.astype(float)
print(arr1,arr1.dtype)

In [ ]:
# 정수와 실수로 구성된 list_e = [1.2,2.3,3]을 numpy를 이용해서 실수형과 정수형으로 각각 출력하세요
arr1 = np.array([1.2,2.3,3])
print(arr1,arr1.dtype)
arr2 = arr1.astype(int)
print(arr2,arr2.dtype)

In [ ]:
# 배열의 산술 연산 복습시험출제
arr = np.array([[1,2,3],[4,5,6]])
arr = np.arange(1,7).reshape(2,3)
print(arr,arr.dtype)

In [ ]:
arr * arr

In [ ]:
arr-arr

In [ ]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

In [ ]:
arr2 > arr 복습시험출제

In [ ]:
# 기본 사칙연산 복습시험출제
value1 = np.arange(1,10).reshape(3,3)
value2 = np.arange(11,20).reshape(3,3)

print(value2+value1,'\n')
print(np.add(value1,value2),'\n')

print(value2-value1,'\n')
print(np.subtract(value2,value1),'\n')

print(value2*value1,'\n')
print(np.multiply(value1,value2),'\n')

print(value2/value1,'\n')
print(np.divide(value2,value1),'\n')

In [ ]:
arr = np.random.randn(2,2)
arr

In [ ]:
arr.mean().round(4)

In [ ]:
arr.mean(axis = 1).round(4)

In [ ]:
arr.mean(axis = 0).round(4)

In [ ]:
arr.sum().round(4)

In [13]:
# 누적해서 곱한것 복습시험출제
# print(arr.cumprod())
ar1 = np.arange(1,5).reshape(2,2)
print(ar1,'\n',ar1.cumprod())

[[1 2]
 [3 4]] 
 [ 1  2  6 24]


In [14]:
# 인덱싱, 슬라이싱 복습시험출제
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[2]

In [ ]:
arr2d[2][2]

In [ ]:
arr2d[:,0]

In [ ]:
arr2d[:,0]   # [ 행 , 열]

In [ ]:
arr2d[:2,:]

In [15]:
# arr2d를 다른방식으로 아래와 같이 출력하세요.
# [[1,2,3],
#  [4,5,6]]
arr2d[[0,2],:]

array([[1, 2, 3],
       [7, 8, 9]])

In [16]:
# arr2d에서 [3,6],[[1,2],[4,5]]을 출력하세요.
print(arr2d[:2,2])
print(arr2d[:2,:2])

[3 6]
[[1 2]
 [4 5]]


In [ ]:
arr = np.arange(30).reshape(5,6)
arr

In [ ]:
# [14,15,16]
# [3,9]
# [1,7,13]
print(arr[2,[2,3,4]])
print(arr[2][2:5])

print(arr[[0,1],3])

print(arr[[0,1,2],1])
print(arr[:3,1])

In [ ]:
# 배열을 리스트로 변환 복습시험출제
li = arr.tolist()
print(li)
type(li)

In [ ]:
# Boolean indexing 복습시험출제
arr1d = np.arange(1,10)
print(arr1d)
arr3 = arr1d[arr1d > 5]
print(arr3)
print(arr1d > 5)

In [ ]:
# arr1d에서 일반 인덱스를 이용해서 [6,7,8,9]를 출력하세요
arr1d[5:]

In [ ]:
# Q. 1~ 14 까지 ndarray를 만들어 array_e로 저장하고 (array_e/2)>5를 만족하는 값을 불린 인덱스로 출력하세요
array_e = np.arange(1,15)
arr1 = array_e[(array_e/2)>5]
print(arr1)

In [ ]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
print(names,'\n')
print(data)

In [ ]:
names == 'Bob'

In [ ]:
data[names == 'Bob']

In [ ]:
data[names =='Bob', 2:]

In [ ]:
# != 부정 복습시험출제
data[names != 'Bob']

In [ ]:
# Bob이거나 Will인 것 출력 # | or과 같은역할 복습시험출제
mask = (names == 'Bob')|(names == 'Will')
data[mask]

In [ ]:
# 음수를 모두 0으로 처리하여 출력
data[data<0]=0
print(data)

In [ ]:
# [과제] 1 ~ 100까지 정수에서 3의 배수인 것만을 출력(for문과 배열 두가지 방식)
li = []
for i in range(1,101):
    if i%3 == 0:
        li.append(i)
print(li)

In [2]:
import numpy as np
arr1 = np.arange(1,101)
arr2 = arr1[arr1%3==0]
print(arr2)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [ ]:
# [과제] 1 ~ 100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두가지 방식)

#배열
arr1 = np.arange(1,101)
arr2 = arr1[(arr1%2==0)&(arr1%5==0)]
print(arr2)
# for문
li = []
for i in range(1,101):
    if i%2 == 0 and i%5==0:
        li.append(i)
print(li)

In [12]:
# [과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요.
arr1 = np.random.randn(5,5)
ㅔ갸ㅜㅅ
print(arr1.mean())
print(arr1.std())

0.2547603576266615
1.1464478843578316


In [ ]:
# [과제] 현재 사용하고 있는 numpy의 버전을 출력하세요.
print(numpy.version.version)

In [3]:
# [과제] numpy 함수의 도움말 기능을 볼수 있는 방법을 수행하여 add 함수의 가이드를 출력하세요.
np.info(np.add)
np.info('add')

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

In [ ]:
# [과제] zeros 함수를 이용해서 아래와 같이 출력하세요.
# array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])
arr = np.zeros(10)
arr[4]=1
arr

In [4]:
# [과제] 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요. 복습시험출제
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [5]:
# [과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.
arr = np.array([1,2,0,0,4,0])
arr[arr>0]

array([1, 2, 4])

In [10]:
# nonzero 는 0이아닌 값의 인덱스를 반환
a= np.array([1,2,0,0,4,0])
np.nonzero(a) 

(array([0, 1, 4], dtype=int64),)

In [15]:
# Fancy Indexing 복습시험출제 밑에 다 볼것 오래함
arr = np.empty((8,4))
arr
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [16]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [17]:
arr[[-1,-5,-6]]

array([[7., 7., 7., 7.],
       [3., 3., 3., 3.],
       [2., 2., 2., 2.]])

In [28]:
arr = np.arange(32).reshape((8,4))
print(arr,'\n')
arr[[1,5,7,2],[0,3,1,2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 



array([ 4, 23, 29, 10])

In [24]:
print(arr[[1,5,7,2]],'\n')
print(arr[[1,5,7,2]][:,[0,3,1,2]])#열 순서 뒤바꾸기

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]] 

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [27]:
# 배열 전치와 축 바꾸기
arr = np.arange(15).reshape((3,5))
print(arr,'\n')
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
