In [15]:
import numpy as np
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3],[4,5,6]])
array3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array1,array1.ndim)
print(array2,array2.ndim)
print(array3,array3.ndim)

[1 2 3] 1
[[1 2 3]
 [4 5 6]] 2
[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 3


In [20]:
array_int = np.array([1,2,3])

array_float = array_int.astype(float)
print(array_float.dtype)

array_int2 = array_float.astype(int)
print(array_int2.dtype)

float64
int32


In [22]:
zero_array = np.zeros((3,2),dtype=int)

print(zero_array)

[[0 0]
 [0 0]
 [0 0]]


In [26]:
one_array = np.ones((3,2))

print(one_array,one_array.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]] float64


In [38]:
# reshape
ar1 = np.arange(10)
print(ar1,ar1.ndim,'\n')
ar2 = ar1.reshape(2,5)
print(ar2,ar2.ndim,'\n')
ar3 = ar2.reshape(1,2,5)
print(ar3,ar3.ndim)

[0 1 2 3 4 5 6 7 8 9] 1 

[[0 1 2 3 4]
 [5 6 7 8 9]] 2 

[[[0 1 2 3 4]
  [5 6 7 8 9]]] 3


In [37]:
# reshape, -1
ar1 = np.arange(10)
print(ar1,ar1.ndim,'\n')
ar2 = ar1.reshape(2,-1)
print(ar2,ar2.ndim,'\n')
ar3 = ar2.reshape(1,2,-1)
print(ar3,ar3.ndim)

[0 1 2 3 4 5 6 7 8 9] 1 

[[0 1 2 3 4]
 [5 6 7 8 9]] 2 

[[[0 1 2 3 4]
  [5 6 7 8 9]]] 3


In [43]:
# 3차원 -> 2,1차원
ar3 = np.arange(8).reshape((2,2,2))
print(ar3,ar3.ndim,'\n')
ar2 = ar3.reshape(2,-1)
print(ar2,ar2.ndim,'\n')
ar1 = ar3.reshape(-1)
print(ar1,ar1.ndim)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 3 

[[0 1 2 3]
 [4 5 6 7]] 2 

[0 1 2 3 4 5 6 7] 1


In [49]:
# indexing
ar1 = np.arange(1,10)
print(ar1)
print(ar1[1])
print(ar1[-1])
print(ar1[-3])

[1 2 3 4 5 6 7 8 9]
2
9
7


In [64]:
ar2d = np.arange(1,10).reshape(3,3)
print(ar2d)
print(ar2d[0,0])
print(ar2d[0,1])
print(ar2d[1,0])
print(ar2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


In [72]:
# slicing
ar1 = np.arange(1,20)
print(ar1)
print(ar1[3:6])
print(ar1[-4:-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[4 5 6]
[16 17 18]


In [86]:
ar2d = np.arange(1,10).reshape(3,3)
print(ar2d)
print(ar2d[:2,:2])
print(ar2d[1:,:])
print(ar2d[:2,1:])
print(ar2d[:2,:1])
print(ar2d[:2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[[1]
 [4]]
[1 4]


In [107]:
# fancy indexing
ar2 = np.arange(1,10).reshape(3,3)
print(ar2)
print(ar1[[0,1],2])
print(ar1[[0,1],:2])
print(ar1[[0,1]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [87]:
# boolean indexing
ar1 = np.arange(1,10)
print(ar1)
print(ar1[ar1>5])

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [115]:
# np.sort() : 원본 미반영
ar = np.array([3,1,9,5])
print(ar)
sort_ar = np.sort(ar)
print(sort_ar)
print(ar)

# ndarray.sort() : 원본 반영
sort_ar1 = ar.sort()
print(sort_ar1)
print(ar)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [117]:
# 내림차순 정렬
sort_ar_desc = np.sort(ar)[::-1]
print(sort_ar_desc)

[9 5 3 1]


In [122]:
ar2 = np.array([[8,12],
[7,1]])
print(ar2,'\n')
sort_ar2_axis0 = np.sort(ar2,axis=0)
print(sort_ar2_axis0,'\n')
sort_ar2_axis1 = np.sort(ar2,axis=1)
print(sort_ar2_axis1)

[[ 8 12]
 [ 7  1]] 

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


In [128]:
# 정렬 행렬의 인덱스 반환
ar = np.array([3,1,9,5])
print(ar)
sort_indices = np.argsort(ar)
print(sort_indices)

[3 1 9 5]
[1 0 3 2]


In [130]:
# 행렬 내적
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8],[9,10],[11,13]])
np.dot(a,b)

array([[ 58,  67],
       [139, 160]])

In [137]:
# 전치 행렬
a = np.array([[1,2],[3,4]])
print(a.T)

[[1 3]
 [2 4]]
