In [34]:
# 지금은 slots_score가 None으로 이루어진 행렬입니다. 아래의 예시를 바탕으로 y_slots를 이용하여 slots_score를 만들어보세요.
# 예시)
#           입력 문장: 아이유 노래 재생
#           토크나이즈 된 문장: ['아이유_ / 노래_ / 재 / 생_']
import numpy as np
slots = [['아티스트', 'O', 'O', 'O']]
y_slots = [[[0.00003171, 0.00454775, 0.9950228,  0.00019214, 0.00020573],
            [0.00000268, 0.9998349,  0.00004407, 0.00001392, 0.00010439],
            [0.00000056, 0.9999397,  0.00002303, 0.00000644, 0.00003024],
            [0.00000094, 0.99993575, 0.00002988, 0.00001607, 0.00001725]]]
slots_score = [[0.9950228,  0.9998349,  0.9999397,  0.99993575]] #-> 각 토큰의 슬롯에 대한 확률

In [49]:
y_slots = np.array(y_slots)
y_slots.shape[1]

4

In [51]:
slots_score = [y_slots[0][i].max() for i in range(y_slots.shape[1])]

In [52]:
slots_score

[0.9950228, 0.9998349, 0.9999397, 0.99993575]

In [72]:
y_slots = [[np.array([5.6677035e-08, 9.9999344e-01, 1.3249938e-07, 1.1502808e-06,2.9978137e-06, 5.1745207e-07, 1.8325231e-06]), 
np.array([5.5051739e-08, 9.9998486e-01, 5.3082005e-07, 4.3844011e-06,7.4759205e-06, 1.9601803e-06, 8.8876635e-07]), 
np.array([3.2441665e-07, 9.9993825e-01, 7.4826830e-06, 2.2793694e-05,1.0244708e-05, 2.0070049e-05, 8.2044193e-07]), 
np.array([1.6089143e-07, 9.9996006e-01, 3.8362846e-06, 1.4872124e-05,1.2326379e-05, 8.5610063e-06, 2.7684803e-07]), 
np.array([1.2657162e-07, 9.9998498e-01, 4.7938221e-07, 3.7399307e-06,3.4395814e-06, 7.0355877e-06, 2.4988418e-07]), 
np.array([2.7761866e-06, 4.5242600e-06, 4.7548006e-06, 1.9611074e-05,1.3295256e-05, 9.9992692e-01, 2.8181592e-05]), 
np.array([3.6121246e-06, 4.2213142e-06, 2.5066145e-06, 4.5790941e-05,1.1241455e-05, 9.9977332e-01, 1.5938240e-04]), 
np.array([3.1479583e-06, 6.1210289e-06, 1.6561071e-06, 6.7100271e-05,2.8119783e-05, 1.9687033e-05, 9.9987411e-01]), 
np.array([1.3274414e-06, 1.5770269e-06, 3.4443494e-06, 2.4338100e-05,3.4518849e-05, 7.3630972e-06, 9.9992740e-01]), 
np.array([4.0329742e-06, 1.7327106e-06, 2.4855060e-06, 1.6266904e-05,2.0826690e-05, 4.4722642e-06, 9.9995017e-01]), 
np.array([1.2412953e-06, 6.9294435e-07, 8.1452578e-07, 1.5454531e-05,1.5707801e-05, 7.4386085e-06, 9.9995863e-01]), 
np.array([4.4270308e-08, 9.9999166e-01, 2.7190066e-07, 7.8793300e-07,2.1871942e-06, 3.0997765e-07, 4.7899080e-06]), 
np.array([1.0004122e-08, 9.9998891e-01, 1.6182231e-07, 6.3843157e-07,7.7009809e-06, 2.7288917e-07, 2.3337384e-06]), 
np.array([3.6869635e-06, 6.0420196e-05, 1.2535944e-05, 1.7286689e-05,9.9988604e-01, 1.7962459e-05, 1.9880611e-06]), 
np.array([5.6871618e-06, 6.6949535e-05, 6.1468550e-06, 2.8243920e-05,9.9986255e-01, 2.6753611e-05, 3.6591241e-06]), 
np.array([2.4181661e-06, 8.3206083e-05, 2.0428979e-06, 1.6911985e-05,9.9987960e-01, 1.4494159e-05, 1.3274590e-06]), 
np.array([8.7461061e-08, 1.2088282e-06, 9.9998200e-01, 2.9043172e-06,5.1487837e-06, 8.5510592e-06, 9.8117972e-08]), 
np.array([7.4467550e-08, 5.7167140e-06, 9.9998128e-01, 2.9738583e-06,4.0477225e-06, 5.7715533e-06, 1.4213228e-07]), 
np.array([4.6727369e-08, 7.0262322e-06, 9.9997807e-01, 4.1706062e-06,4.0565051e-06, 6.3667453e-06, 3.0902277e-07]), 
np.array([1.1927252e-08, 9.9999630e-01, 4.9657780e-07, 4.8378985e-07,2.3640030e-06, 2.6792196e-07, 9.7415800e-08]), 
np.array([6.5493984e-09, 9.9999845e-01, 3.3496164e-07, 1.4949840e-07,7.9940605e-07, 1.2705188e-07, 6.9016927e-08]), 
np.array([8.9941459e-09, 9.9999940e-01, 1.2822690e-07, 1.2661378e-07,3.1498587e-07, 4.9174016e-08, 3.2324486e-08]), 
np.array([1.0295960e-08, 9.9999952e-01, 8.8933682e-08, 9.8252464e-08,2.6991549e-07, 4.3640952e-08, 3.5927453e-08]), 
np.array([2.7728799e-08, 9.9999869e-01, 2.4854643e-07, 2.5611840e-07,5.7182496e-07, 9.2762505e-08, 7.2105024e-08])],
[np.array([9.2538794e-06, 2.3261766e-05, 6.0912964e-05, 9.9966979e-01,3.2918845e-06, 1.0855473e-04, 1.2486069e-04]), 
np.array([6.1962496e-06, 1.1033332e-05, 2.4718525e-05, 9.9992490e-01,6.5211184e-06, 1.1257234e-05, 1.5435096e-05]), 
np.array([7.7558497e-08, 9.9998951e-01, 4.2752191e-07, 1.5268171e-06,5.2293708e-06, 5.1968937e-07, 2.6662619e-06]), 
np.array([1.25915562e-08, 9.99995708e-01, 1.08707866e-07, 6.02843556e-07,2.81952384e-06, 3.53216564e-07, 3.84757243e-07]), 
np.array([2.8331367e-08, 9.9999332e-01, 2.0983876e-07, 3.8936396e-06,1.6630091e-06, 7.6119085e-07, 7.6324469e-08]), 
np.array([1.6002437e-07, 3.4481903e-07, 1.4497002e-06, 9.7713446e-06,9.0961585e-06, 9.9995804e-01, 2.1041893e-05]), 
np.array([1.0906567e-06, 4.3945730e-07, 3.2507687e-06, 1.4085537e-05,2.4674207e-05, 9.9990511e-01, 5.1321007e-05]), 
np.array([5.2216865e-07, 2.7570465e-07, 1.1145218e-06, 7.4382106e-06,1.7306847e-05, 9.9995565e-01, 1.7634431e-05]), 
np.array([5.6114583e-08, 3.2706198e-06, 9.9994397e-01, 5.2694318e-06,4.0291898e-06, 4.3098735e-05, 2.3135912e-07]), 
np.array([4.1134996e-08, 2.7647193e-06, 9.9998677e-01, 2.0138330e-06,1.9412701e-06, 6.3419484e-06, 1.4268090e-07]), 
np.array([3.9381018e-08, 7.4717542e-07, 9.9998677e-01, 3.4404766e-06,1.8906071e-06, 6.8433660e-06, 2.0777419e-07]), 
np.array([5.0698198e-08, 9.9998963e-01, 3.8905534e-07, 6.8109063e-07,6.7691171e-06, 4.6712429e-07, 2.0820037e-06]), 
np.array([2.8155884e-09, 9.9999666e-01, 1.4768219e-07, 2.1979811e-07,2.3661034e-06, 1.6642879e-07, 4.9213077e-07]), 
np.array([5.4914677e-09, 9.9999881e-01, 2.5962183e-07, 2.5394965e-07,6.3456457e-07, 1.7751383e-07, 5.2189019e-08]), 
np.array([3.9995549e-09, 9.9999917e-01, 2.6435421e-07, 1.3222633e-07,3.6742816e-07, 1.0278988e-07, 4.1790948e-08]), 
np.array([7.9634344e-09, 9.9999952e-01, 1.4306178e-07, 1.3328977e-07,2.1003187e-07, 4.9335043e-08, 2.3628811e-08]), 
np.array([9.0085335e-09, 9.9999952e-01, 9.8678036e-08, 1.3808172e-07,2.5059779e-07, 5.1249767e-08, 3.4482820e-08]), 
np.array([1.6788695e-08, 9.9999917e-01, 1.6104526e-07, 2.2598695e-07,3.6979858e-07, 7.4175155e-08, 5.6017903e-08])]]

In [73]:
len(y_slots)

2

In [77]:
y_slots[0][0].max()

0.99999344

In [83]:
slots_score = []
for i in range(len(y_slots)):
    slot_score = []
    for j in range(len(y_slots[i])):
        slot_score.append(y_slots[i][j].max())
    slots_score.append(slot_score)

In [84]:
slots_score

[[0.99999344,
  0.99998486,
  0.99993825,
  0.99996006,
  0.99998498,
  0.99992692,
  0.99977332,
  0.99987411,
  0.9999274,
  0.99995017,
  0.99995863,
  0.99999166,
  0.99998891,
  0.99988604,
  0.99986255,
  0.9998796,
  0.999982,
  0.99998128,
  0.99997807,
  0.9999963,
  0.99999845,
  0.9999994,
  0.99999952,
  0.99999869],
 [0.99966979,
  0.9999249,
  0.99998951,
  0.999995708,
  0.99999332,
  0.99995804,
  0.99990511,
  0.99995565,
  0.99994397,
  0.99998677,
  0.99998677,
  0.99998963,
  0.99999666,
  0.99999881,
  0.99999917,
  0.99999952,
  0.99999952,
  0.99999917]]

In [79]:
slots_score

[0.9950228, 0.9998349, 0.9999397, 0.99993575, [0.99999869], [0.99999917]]

In [ ]:
model.fit(x_train, y_train
          val = (x_val,y_val))

In [69]:
slots_score = []

IndexError: list index out of range

In [67]:
slots_score = [[None]*len(slots[i]) for i in range(y_slots.shape[0])]

IndexError: list index out of range

In [64]:
y_slots

[[array([5.6677035e-08, 9.9999344e-01, 1.3249938e-07, 1.1502808e-06,
         2.9978137e-06, 5.1745207e-07, 1.8325231e-06]),
  array([5.5051739e-08, 9.9998486e-01, 5.3082005e-07, 4.3844011e-06,
         7.4759205e-06, 1.9601803e-06, 8.8876635e-07]),
  array([3.2441665e-07, 9.9993825e-01, 7.4826830e-06, 2.2793694e-05,
         1.0244708e-05, 2.0070049e-05, 8.2044193e-07]),
  array([1.6089143e-07, 9.9996006e-01, 3.8362846e-06, 1.4872124e-05,
         1.2326379e-05, 8.5610063e-06, 2.7684803e-07]),
  array([1.2657162e-07, 9.9998498e-01, 4.7938221e-07, 3.7399307e-06,
         3.4395814e-06, 7.0355877e-06, 2.4988418e-07]),
  array([2.7761866e-06, 4.5242600e-06, 4.7548006e-06, 1.9611074e-05,
         1.3295256e-05, 9.9992692e-01, 2.8181592e-05]),
  array([3.6121246e-06, 4.2213142e-06, 2.5066145e-06, 4.5790941e-05,
         1.1241455e-05, 9.9977332e-01, 1.5938240e-04]),
  array([3.1479583e-06, 6.1210289e-06, 1.6561071e-06, 6.7100271e-05,
         2.8119783e-05, 1.9687033e-05, 9.9987411e-01]),


In [56]:
y_slots[0][0]

array([5.6677035e-08, 9.9999344e-01, 1.3249938e-07, 1.1502808e-06,
       2.9978137e-06, 5.1745207e-07, 1.8325231e-06])

In [54]:
slots_score = [y_slots[0][i].max() for i in range(y_slots.shape[1])]

AttributeError: 'list' object has no attribute 'shape'