## 판다스
- 판다스는 구조화된 데이터 형식을 제공. 시리즈는 1차원 배열, 데이터프레임은 2차원배열
- 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
- 시리즈 인덱스는 데이터값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)
- Contents
    - Series(변환, 인덱스 구조, 원소 선택)
    - DataFrame(변환,인덱스,삭제,선택,추가,변경,전치 등)
    #복습시험출제

In [1]:
import pandas as pd
import numpy as np

In [3]:
# 시리즈 클래스 만들기
import pandas as pd
dic_data = {'a':1,'b':2,'c':3}
sr = pd.Series(dic_data)
print(sr,type(sr))

a    1
b    2
c    3
dtype: int64 <class 'pandas.core.series.Series'>


In [3]:
# 리스트를 시리즈로 변환 #복습시험출제
list_data = ['2019-10-02', 3.14 , 'ABC', 100,True]
sr = pd.Series(list_data, index=['a','b','c','d','e'])
print(sr)

a    2019-10-02
b          3.14
c           ABC
d           100
e          True
dtype: object


In [7]:
idx = sr.index #복습시험출제
print(idx)
val = sr.values
print(val)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


array(['2019-10-02', 3.14, 'ABC', 100, True], dtype=object)

In [7]:
# 튜플을 시리즈로 변환 #복습시험출제
tup_data = ('영인','2015-05-01','여',True)
sr = pd.Series(tup_data,index=['이름','생년월일','성별','학생여부'])
print(sr,type(sr))

이름              영인
생년월일    2015-05-01
성별               여
학생여부          True
dtype: object <class 'pandas.core.series.Series'>


In [21]:
print(sr[0])
print(sr['이름'])
print(sr[[1,3]])

영인
영인
생년월일    2015-05-01
학생여부          True
dtype: object


In [22]:
# 배열을 시리즈로 변환 #복습시험출제
import numpy as np

s1 = np.arange(start = 11, stop = 16)
s2 = pd.Series(s1,index=['ED1','ED2','ED3','ED4','ED5'])
print(s1,type(s1),'\n')
print(s2,type(s2))

[11 12 13 14 15] <class 'numpy.ndarray'> 

ED1    11
ED2    12
ED3    13
ED4    14
ED5    15
dtype: int32 <class 'pandas.core.series.Series'>


In [23]:
print(s2[1:3],'\n')
print(s2[[1,3]])

ED2    12
ED3    13
dtype: int32 

ED2    12
ED4    14
dtype: int32


In [26]:
# 시리즈 -> 배열 
ar = np.array(s2)
ar

array([11, 12, 13, 14, 15])

In [18]:
# Q. 4가지 자료형 데이터를 생성하고 각각 Series로 변환하여 출력하세요.
import numpy as np
import pandas as pd
a1 = [1,2,3]
a2 = {'a':1,'b':2,'c':3}
a3 = (1,2,3)
a4 = np.arange(1,4)
s1 = pd.Series(a1)
s2 = pd.Series(a2)
s3 = pd.Series(a3)
s4 = pd.Series(a4)
print(s1,type(s1),'\n')
print(s2,type(s2),'\n')
print(s3,type(s3),'\n')
print(s4,type(s4),'\n')

0    1
1    2
2    3
dtype: int64 <class 'pandas.core.series.Series'> 

a    1
b    2
c    3
dtype: int64 <class 'pandas.core.series.Series'> 

0    1
1    2
2    3
dtype: int64 <class 'pandas.core.series.Series'> 

0    1
1    2
2    3
dtype: int32 <class 'pandas.core.series.Series'> 



In [37]:
data = np.arange(1000,5000,1000)
obj = pd.Series(data)
state = ['Califonia','Ohio','Oregon','Texas']
obj.name = 'population'
obj.index = state
obj.index.name = 'state'
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int32

In [38]:
obj['Califonia']

1000

In [39]:
obj['Newyork'] = 3000

In [40]:
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Newyork      3000
Name: population, dtype: int64

In [41]:
obj.Califonia = np.nan #복습시험출제
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Newyork      3000.0
Name: population, dtype: float64

In [42]:
print(obj.isnull()) #복습시험출제
print()
print(obj.isnull().sum())

state
Califonia     True
Ohio         False
Oregon       False
Texas        False
Newyork      False
Name: population, dtype: bool

1


## 데이터프레임
- 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래
- 데이터프레임의 열은 각각 시리즈 개체
- 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를 기준으로 줄지어 결합된 2차원 벡터 또는 행렬
- 선형대수학에서 열 벡터(mx1행렬)는 m 원소들의 단일 열 행렬
- 행벡터(1xm 행렬)은 m원소들의 단일 행 행렬
- 리스트, 딕셔너리 , 배열들 다양한 데이터로부터 생성
- 반대로 리스트, 딕셔너리, 배열 등으로 변환될 수 있음

In [2]:
# 배열 -> 데이터프레임 #복습시험출제
 
ar = np.random.randint(100,120,size = (3,3))
print(ar,type(ar),'\n')
df = pd.DataFrame(ar,index=['d1','d2','d3'],
                 columns=['pd','sales','int'])
print(df,type(df))
df

[[101 101 107]
 [117 119 116]
 [116 106 104]] <class 'numpy.ndarray'> 

     pd  sales  int
d1  101    101  107
d2  117    119  116
d3  116    106  104 <class 'pandas.core.frame.DataFrame'>


pd  sales  int
d1  101    101  107
d2  117    119  116
d3  116    106  104

pandas indexing
- iloc : integer location의 약어, 데이터프레임의 행이나 칼럼의 순서를 나타내는 정수로 특정 값을 추출해오는 방법
- loc : 칼럼명을 직접 적거나 특정 조건식을 써줌으로써 사람이 읽기 좋은 방법으로 데이터에 접근하는 방법

In [54]:
# 행선택
print(df.iloc[1],'\n')
print(df.loc['d2'])

pd       108
sales    117
int      112
Name: d2, dtype: int32 

pd       108
sales    117
int      112
Name: d2, dtype: int32


In [55]:
# 특정 행, 열 선택
print(df.iloc[1,1],'\n')
print(df.loc['d2','sales'])

117 

117


In [8]:
# 행, 열 추가
df1 = df.copy()
df1.loc['d5']=0
df1
# 새로운 열 생성시에는 대괄호
df1['pf'] = [100,100,100,0]
df1

pd  sales  int   pf
d1  101    101  107  100
d2  117    119  116  100
d3  116    106  104  100
d5    0      0    0    0

In [9]:
# 원소 값 변경
df1.iloc[1,1] = np.nan
df1

pd  sales  int   pf
d1  101  101.0  107  100
d2  117    NaN  116  100
d3  116  106.0  104  100
d5    0    0.0    0    0

In [14]:
# 사전 - > 데이터프레임 #복습시험출제
sp1 = np.arange(1,6)
df = pd.DataFrame({
    'col1':sp1 ,
    'col2':sp1 *2,
    'col3':['A','B','C','D','E']
})
df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [71]:
# 딕셔너리에서 값이 스칼라이면 인덱스 필요

dic = {'A':1,'B':2,'C':3,'D':4}
# dic = {'A':[1],'B':[2],'C':[3],'D':[4]}
columns=['a','b','c','d','e']
index=[1,2,3,4]

df_dic = pd.DataFrame(dic,index)
# df_dic = pd.DataFrame(dic)
print(df_dic)

   A  B  C  D
1  1  2  3  4
2  1  2  3  4
3  1  2  3  4
4  1  2  3  4


In [9]:
# 리스트 -> 데이터프레임 #복습시험출제
a = np.random.randint(1,5,size=(10,5))
list1 = a.tolist()
index = np.arange(1,11)
df = pd.DataFrame(list1,index,columns=['c1','c2','c3','c4','c5'])
df

c1  c2  c3  c4  c5
1    1   3   3   3   1
2    3   3   2   3   1
3    3   1   2   1   1
4    3   3   3   2   2
5    4   4   4   4   1
6    1   2   1   3   1
7    3   2   1   4   2
8    1   4   2   1   3
9    2   4   4   1   2
10   1   1   2   4   4

In [16]:
# 데이터프레임 -> 배열, 리스트, 딕셔너리 #복습시험출제
ar = df.values
print(ar, type(ar),'\n')
li = df.values.tolist()
print(li, type(li),'\n')
dict = df.to_dict('list')
print(dict,type(dict))

[[1 3 3 3 1]
 [3 3 2 3 1]
 [3 1 2 1 1]
 [3 3 3 2 2]
 [4 4 4 4 1]
 [1 2 1 3 1]
 [3 2 1 4 2]
 [1 4 2 1 3]
 [2 4 4 1 2]
 [1 1 2 4 4]] <class 'numpy.ndarray'> 

[[1, 3, 3, 3, 1], [3, 3, 2, 3, 1], [3, 1, 2, 1, 1], [3, 3, 3, 2, 2], [4, 4, 4, 4, 1], [1, 2, 1, 3, 1], [3, 2, 1, 4, 2], [1, 4, 2, 1, 3], [2, 4, 4, 1, 2], [1, 1, 2, 4, 4]] <class 'list'> 

{'c1': [1, 3, 3, 3, 4, 1, 3, 1, 2, 1], 'c2': [3, 3, 1, 3, 4, 2, 2, 4, 4, 1], 'c3': [3, 2, 2, 3, 4, 1, 1, 2, 4, 2], 'c4': [3, 3, 1, 2, 4, 3, 4, 1, 1, 4], 'c5': [1, 1, 1, 2, 1, 1, 2, 3, 2, 4]} <class 'dict'>


In [63]:
# Q. 배열, 리스트, 딕셔너리로 데이터프레임을 생성한 후 다시 배열, 리스트, 딕셔너리로 변환하여 출력하세요.
arr = np.arange(9).reshape(3,3)
li = arr.tolist()
dic = {'d1':[0,3,6],'d2':[1,4,7],'d3':[2,5,8]}
index = [1,2,3]
columns = ['d1','d2','d3']
df1 = pd.DataFrame(arr,index,columns = columns)
print(df1)
df2 = pd.DataFrame(li,index,columns=columns)
print(df2)
df3 = pd.DataFrame(dic,index)
print(df3)
arr1 = df1.values
print(arr1)
li1 = df2.values.tolist()
print(li1)
dic1 = df3.to_dict('list')
print(dic1)

   d1  d2  d3
1   0   1   2
2   3   4   5
3   6   7   8
   d1  d2  d3
1   0   1   2
2   3   4   5
3   6   7   8
   d1  d2  d3
1   0   1   2
2   3   4   5
3   6   7   8
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
{'d1': [0, 3, 6], 'd2': [1, 4, 7], 'd3': [2, 5, 8]}


In [48]:
arr1 = df1.values
print(arr1)
li1 = df2.values.tolist()
print(li1)
dic1 = df3.to_dict('list')
print(dic1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
{'d1': [0, 3, 6], 'd2': [1, 4, 7], 'd3': [2, 5, 8]}


In [65]:
# file 생성 #복습시험출제
arr = np.arange(9).reshape(3,3)
index = [1,2,3]
columns = ['d1','d2','d3']
df1 = pd.DataFrame(arr,index,columns = columns)
df1.to_csv("./dataset/flie_data.csv",index=None)
file_data = pd.read_csv('./dataset/flie_data.csv')
file_data

d1  d2  d3
0   0   1   2
1   3   4   5
2   6   7   8

In [4]:
import pandas as pd
li = ['냉면','칼국수','잔치국수','수제비','우동']
df1 = pd.DataFrame(li,index=['메뉴1','메뉴2','메뉴3','메뉴4','메뉴5'],columns=['차림표'])
df1.to_csv("./dataset/file_data.csv",index=None)
file_data = pd.read_csv('./dataset/file_data.csv')
file_data

차림표
0    냉면
1   칼국수
2  잔치국수
3   수제비
4    우동

In [5]:
import pandas as pd
li = ['냉면','칼국수','잔치국수','수제비','우동']
df1 = pd.DataFrame(li,index=['메뉴1','메뉴2','메뉴3','메뉴4','메뉴5'],columns=['차림표'])
df1.to_csv("./dataset/file_data.csv")
file_data = pd.read_csv('./dataset/file_data.csv',index_col=0)
file_data

차림표
메뉴1    냉면
메뉴2   칼국수
메뉴3  잔치국수
메뉴4   수제비
메뉴5    우동